language: ruby
before_install: 
  - gem install ceedling
install:
  - mkdir build
  - bundler install
script:
  - bundler exec rake travis
after_success:
  - coveralls-lcov coverage.info
# language: c
# script: ceedling test:all
# before_install:
# - gem install ceedling coveralls thor
